version: '3'
services:
  wpp_bot:
    build: .
    container_name: wpp_bot
    restart: always
    environment:
      - DB_USER=kiko
      - DB_PASSWORD=${SECRET}
      - GROUP_JID=120363046897347696@g.us
      - BACKEND_URI="http://localhost:8080/"

  wpp_bot_db:
    image: arm64v8/postgres:latest
    container_name: wpp_bot_db
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=kiko
      - POSTGRES_DB=devices
      - POSTGRES_PASSWORD=${SECRET}
    volumes:
      - /data/wpp-bot:/var/lib/postgresql/data
  
  wpp_bot_db_adminer:
      image: arm64v8/adminer:latest
      restart: always
      container_name: wpp_bot_db_adminer
      ports:
        - 8888:8080
      environment:
        - ADMINER_DESIGN=nette
        - ADMINER_DEFAULT_SERVER=wpp_bot_db
